//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestOA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTestOAEntities : DbContext
    {
        public DBTestOAEntities()
            : base("name=DBTestOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<KeyWordsRank> KeyWordsRank { get; set; }
        public virtual DbSet<SearchDetails> SearchDetails { get; set; }
    }
}
